service: counter-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: deploy-dev

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  authentication:
    handler: build/index.authentication
    events:
      - httpApi:
          path: /auth
          method: post
  incrementVisits:
    handler: build/index.incrementVisits
    events:
      - httpApi:
          path: /visits/{namespace}
          method: put
  getVisits:
    handler: build/index.getVisits
    events:
      - httpApi:
          path: /visits/{namespace}
          method: get
  createUser:
    handler: build/index.createUser
    events:
      - httpApi:
          path: /users
          method: post
  showUser:
    handler: build/index.showUser
    events:
      - httpApi:
          path: /users/{id}
          method: get

resources:
  Resources:
    Ton:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceClass: db.t3.micro
        Engine: MySQL
        MasterUsername: admin
        MasterUserPassword: password
