service: counter-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: deploy-dev

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
