service: ton-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${file(sls.${opt:stage}.yml):provider.profile}
  environment:
    NODE_ENV: ${opt:stage}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

package:
  patterns:
    - "!node_modules/@types/**"
    - "!__tests__/**"
    - "!src/**"
    - "!.husky/**"
    - "!coverage/**"
    - "!.editorconfig"
    - "!commitlint.config.js"
    - "!jest.config.js"
    - "!README.md"
    - "!tsconfig.json"

functions: ${file(sls.${opt:stage}.yml):functions}

resources: ${file(sls.${opt:stage}.yml):resources}
